name: Action-workflow
on:
 push:
   branches:
     - main
     - dev
 pull_request:
   types: opened
   branches:
     - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: build step
       run: echo " this is build step"
  test:
   runs-on: ubuntu-lates
   needs: build
   steps:
     - name: test step
       run: echo " this is the test step "
  deploy:
   runs-on: ubuntu-latest
   needs: test
   steps:
     - name: secret & variables test
       run: echo " my name is {{var.name}} and my password is {{secret.password}}"


