name: input demo

on:
  workflow_dispatch:
    inputs:
      environments:
        description: "Choose the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - pod
jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print input
        run: echo "Selected environment is ${{ github.event.inputs.environments }}"
